[build]
  functions = "netlify/functions"
  publish = "build"
  command = "CI=false npm run build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200